### ISSUE TITLE
singularity build fails

### ISSUE THREAD

**Issue by puethe** [rust-bio/rust-htslib#140]
Hi there,
I'm trying to build a singularity image of rust-htslib, but can't get it working and can't make sense of the error message either. Maybe somebody here has an idea? Here's the recipe:

```
BootStrap: docker
From: ubuntu:18.04

%post
apt-get update --quiet --assume-yes
apt-get upgrade --quiet --assume-yes
apt-get install --quiet --assume-yes clang git curl libz-dev libbz2-dev lzma-dev liblzma-dev
curl https://sh.rustup.rs -sSf | sh -s -- -y
. $HOME/.cargo/env
git clone --recursive https://github.com/rust-bio/rust-htslib.git
cd rust-htslib
RUST_BACKTRACE=1 cargo build --release
```

And here comes the error message:

```
error: failed to run custom build command for `rust-htslib v0.24.1-alpha.0 (/rust-htslib)`
process didn't exit successfully: `/rust-htslib/target/release/build/rust-htslib-3ac6015fc511acb8/build-script-build` (exit code: 101)
--- stdout
OPT_LEVEL = Some("3")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CC_x86_64-unknown-linux-gnu = None
CC_x86_64_unknown_linux_gnu = None
HOST_CC = None
CC = None
CFLAGS_x86_64-unknown-linux-gnu = None
CFLAGS_x86_64_unknown_linux_gnu = None
HOST_CFLAGS = None
CFLAGS = None
CRATE_CC_NO_DEFAULTS = None
DEBUG = Some("false")

--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/libcore/result.rs:997:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   6: rust_begin_unwind
             at src/libstd/panicking.rs:308
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   8: core::result::unwrap_failed
   9: build_script_build::main
  10: std::rt::lang_start::{{closure}}
  11: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:293
  12: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:87
  13: std::rt::lang_start_internal
             at src/libstd/panicking.rs:272
             at src/libstd/panic.rs:388
             at src/libstd/rt.rs:48
  14: main
  15: __libc_start_main
  16: _start
```

Grateful about any help!
Christoph

**Comment by juliangehring** [comment]
You are missing the `autoconf, automake, make` [dependencies for htslib](https://github.com/rust-bio/htslib/blob/d2c86b33b45ae8d43841ef1d137532c7be0f1a84/INSTALL#L226). After adding these to your build script

    apt-get install --quiet --assume-yes clang git curl zlib1g-dev libbz2-dev liblzma-dev autoconf automake make

it builds fine (on docker, haven't tested on singularity).

**Comment by juliangehring** [comment]
Btw, if you are able to use the [rust docker image](https://hub.docker.com/_/rust) instead of the plain ubuntu image, you can also save yourself some work and don't have to install rust manually.

**Comment by puethe** [comment]
This is great help, thanks a lot!
All working for me now.

**Comment by johanneskoester** [comment]
Thanks guys!
