### ISSUE TITLE
0.47.0 introduced a dependency on libclang

### ISSUE THREAD

**Issue by DaGaMs** [rust-bio/rust-htslib#434]
I tried to upgrade my code's dependency on rust-htslib to version 0.47.0 (from 0.46.0) but now when I do `cargo build -r` on Linux (eg in a docker container) without `clang`, I get:

```
thread 'main' panicked at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/bindgen-0.69.4/lib.rs:622:31:

Unable to find libclang: "couldn't find any valid shared libraries matching: ['[libclang.so](http://libclang.so/)', 'libclang-*.so', '[libclang.so](http://libclang.so/).*', 'libclang-*.so.*'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (invalid: [])"
```

Reverting back to 0.46.0 fixes the issue. I'm not sure what happened here, but I suspect it was not intentional?

**Comment by moold** [comment]
I also got a `cargo build --release` problem when I used `rust-htslib v0.47.0`, reverting to `v0.46.0` solved the problem.
```
  --- stderr
  ./htslib/htslib/hts.h:31:10: fatal error: 'stddef.h' file not found
  thread 'main' panicked at hts-sys-2.1.4/build.rs:275:14:
  Unable to generate bindings.: ClangDiagnostic("./htslib/htslib/hts.h:31:10: fatal error: 'stddef.h' file not found\n")
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```

**Comment by DaGaMs** [comment]
So, this is _probably_ related to this feature request in `bindgen`:

https://github.com/rust-lang/rust-bindgen/issues/918

What I don't understand is: why does 0.46.0 work but 0.47.0 doesn't? If dependency on libclang.a is a general issue of bindgen, then why does 0.46.0 build fine for me? And vice versa, why does adding one header to hts-sys suddenly break things? 🤔

**Comment by DaGaMs** [comment]
Has anyone tested this with 0.48.0? I'm a bit concerned that this issue is preventing us from updating past 0.46.0. We need to deploy to various linux's and docker images, introducing a dependency on libclang will cause a lot of pain...

**Comment by ArtRand** [comment]
Any update here? I have a similar concern as @DaGaMs..

**Comment by AndreaGuarracino** [comment]
Are there any plans to fix this issue in the latest release?

**Comment by esrice** [comment]
Just noting that this still appears to be an issue in v0.49.0. Reverting to v0.46.0 fixes it.

**Comment by mrvollger** [comment]
Just adding that we are also experiencing this issue and therefore using 0.46.

**Comment by wwood** [comment]
Same on 0.50.0, so (maintaining) restriction to 0.46 in our code.
